In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

##Create and Read 

#One Dimensional Aaray

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype


dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

5

##Two Dimensional array

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape #(row,col)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.size

6

##3 Dimensional array

In [23]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3.ndim

3

In [25]:
arr3.shape

(2, 2, 3)

In [26]:
arr3.size

12